<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Stores</description>
   <name>Stores</name>
   <tag></tag>
   <elementGuidId>bef3eb35-fbb0-45eb-bc42-a9380b1c0141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Stores')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
