<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daypartTimeOption</name>
   <tag></tag>
   <elementGuidId>5c9bc0d4-bd3c-4291-9f52-085b82d1d42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[text()='Daypart']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
