<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dayTimeOption</name>
   <tag></tag>
   <elementGuidId>3e64b103-e765-4f41-a018-ce8836102b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[text()='Day']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
