<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>onlineStore</name>
   <tag></tag>
   <elementGuidId>3806e647-caaf-408c-999c-651b8cd324ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ctable']/table//tr/td[3][not(contains(text(),'Dual'))]/../td[8]/table//td//span/a)[1]/../../../../../../../td[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
